services:
  finance-management-web:
    build:
      context: ./client
      target: base
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      PORT: 3000
      AUTH_BACKEND_URL: http://finance-management-api:5000
      NEXTAUTH_URL: http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - finance-management-web-node_modules:/app/node_modules
  finance-management-api:
    build:
      context: ./server
      target: base
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://${MONGO_USERNAME:-root}:${MONGO_PASSWORD:-example}@finance-management-db:27017/${MONGO_DATABASE:-finance}?authSource=admin
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - finance-management-api-node_modules:/app/node_modules
volumes:
  finance-management-web-node_modules:
  finance-management-api-node_modules:
